# Generated by Django 5.2.4 on 2025-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyresensemain', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hyresense_admin', 'Hyresense Admin'), ('hyresense_customercare', 'Hyresense Customercare'), ('employer', 'Employer'), ('hr', 'HR'), ('jobseeker', 'Job Seeker')], default='jobseeker', max_length=25),
        ),
    ]
