# Generated by Django 5.2.4 on 2025-12-25 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyresensemain', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'early_access_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
