# Generated by Django 5.2.4 on 2025-07-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='description',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='description',
            field=models.TextField(default='', help_text='Detailed description of the job role and responsibilities', verbose_name='job description'),
        ),
    ]
