# Generated by Django 5.2.4 on 2025-07-28 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_jobapplication_description_jobpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(db_index=True, default=6, help_text='Name of the company posting this job', max_length=255, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='employer.employerprofile', verbose_name='Company Admin'),
        ),
    ]
