# Generated by Django 5.2.4 on 2025-07-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_jobpost_company_name_alter_jobpost_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypost',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='companypost',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='external link'),
        ),
        migrations.AddField(
            model_name='companypost',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='video URL'),
        ),
    ]
