# Generated by Django 5.2.4 on 2025-08-01 14:16

import django.db.models.deletion
import employer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_companypost_category_companypost_external_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('followed_at', models.DateTimeField(auto_now_add=True, verbose_name='followed at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('notify_new_jobs', models.BooleanField(default=True, verbose_name='notify new jobs')),
                ('notify_company_updates', models.BooleanField(default=True, verbose_name='notify company updates')),
            ],
            options={
                'verbose_name': 'Company Follower',
                'verbose_name_plural': 'Company Followers',
                'ordering': ['-followed_at'],
            },
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='banner',
            field=models.ImageField(blank=True, help_text='Recommended size: 1200x400 pixels', null=True, upload_to='company_banners/', validators=[employer.models.validate_image], verbose_name='company banner'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['followers_count'], name='employer_em_followe_c97772_idx'),
        ),
        migrations.AddField(
            model_name='companyfollower',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='employer.employerprofile', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='companyfollower',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'jobseeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='following_companies', to=settings.AUTH_USER_MODEL, verbose_name='job seeker'),
        ),
        migrations.AddIndex(
            model_name='companyfollower',
            index=models.Index(fields=['company', 'is_active'], name='employer_co_company_63adb5_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfollower',
            index=models.Index(fields=['user', 'is_active'], name='employer_co_user_id_3e56a9_idx'),
        ),
        migrations.AddIndex(
            model_name='companyfollower',
            index=models.Index(fields=['followed_at'], name='employer_co_followe_fb7f73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfollower',
            unique_together={('company', 'user')},
        ),
    ]
