# Generated by Django 5.2.4 on 2025-08-31 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_companyfollower_employerprofile_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='fit_score',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='is_fit',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='remarks',
        ),
    ]
