# Generated by Django 5.2.4 on 2025-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_remove_jobapplication_fit_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('offer_made', 'Offer Made'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('user_rejected', 'User Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=30, verbose_name='status'),
        ),
    ]
