# Generated by Django 5.2.4 on 2025-09-29 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_employerprofile_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('it', 'Information Technology & Services'), ('software', 'Software Development'), ('internet', 'Internet & Web Services'), ('telecom', 'Telecommunications'), ('electronics', 'Electronics & Semiconductors'), ('ai', 'Artificial Intelligence / Machine Learning'), ('finance', 'Banking, Finance & Insurance'), ('investment', 'Investment Management'), ('accounting', 'Accounting'), ('consulting', 'Management Consulting'), ('real_estate', 'Real Estate & Property Management'), ('healthcare', 'Healthcare & Hospitals'), ('pharma', 'Pharmaceuticals'), ('biotech', 'Biotechnology'), ('medical_devices', 'Medical Devices'), ('wellness', 'Health, Wellness & Fitness'), ('education', 'Education & Training'), ('edtech', 'EdTech'), ('research', 'Research & Development'), ('manufacturing', 'Manufacturing'), ('automotive', 'Automotive'), ('aerospace', 'Aerospace & Defense'), ('construction', 'Construction & Engineering'), ('energy', 'Energy & Utilities'), ('oil_gas', 'Oil & Gas'), ('mining', 'Mining & Metals'), ('chemical', 'Chemicals'), ('retail', 'Retail & Wholesale'), ('fmcg', 'FMCG / Consumer Goods'), ('food', 'Food & Beverages'), ('fashion', 'Apparel & Fashion'), ('luxury', 'Luxury Goods & Jewelry'), ('hospitality', 'Hospitality'), ('travel', 'Travel & Tourism'), ('media', 'Media & Publishing'), ('entertainment', 'Entertainment & Film'), ('sports', 'Sports & Recreation'), ('gaming', 'Gaming'), ('marketing', 'Marketing & Advertising'), ('design', 'Design & Creative Services'), ('logistics', 'Logistics & Supply Chain'), ('transport', 'Transportation'), ('shipping', 'Shipping & Marine'), ('aviation', 'Aviation'), ('agriculture', 'Agriculture & Farming'), ('forestry', 'Forestry & Paper'), ('fisheries', 'Fisheries & Aquaculture'), ('environment', 'Environmental Services'), ('renewables', 'Renewable Energy'), ('government', 'Government Administration'), ('ngo', 'Nonprofit / NGO'), ('defense', 'Defense & Security'), ('public_safety', 'Public Safety & Law Enforcement'), ('legal', 'Legal Services'), ('hr', 'Human Resources & Staffing'), ('ecommerce', 'E-commerce'), ('startup', 'Startups'), ('other', 'Other')], db_index=True, max_length=50, null=True, verbose_name='company category'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['category'], name='employer_em_categor_26164e_idx'),
        ),
    ]
