# Generated by Django 5.2.4 on 2025-09-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_employerprofile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_fit',
            field=models.BooleanField(default=False),
        ),
    ]
