# Generated by Django 5.2.4 on 2025-09-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_jobapplication_is_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='fit_score',
            field=models.IntegerField(default=0),
        ),
    ]
