# Generated by Django 5.2.4 on 2025-09-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_jobapplication_fit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
