# Generated by Django 5.2.4 on 2025-10-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_jobapplication_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leadership_photos/')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_team', to='employer.employerprofile')),
            ],
            options={
                'verbose_name': 'Leadership Member',
                'verbose_name_plural': 'Leadership Team',
            },
        ),
    ]
