# Generated by Django 5.2.4 on 2025-10-04 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_employerleadership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(verbose_name='remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_history', to='employer.jobapplication', verbose_name='job application')),
                ('reviewer', models.ForeignKey(limit_choices_to=models.Q(('role__in', ['hr', 'employer', 'interviewer'])), on_delete=django.db.models.deletion.CASCADE, related_name='application_remarks', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'Application Remark',
                'verbose_name_plural': 'Application Remarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'created_at'], name='employer_ap_applica_a363ef_idx'), models.Index(fields=['reviewer'], name='employer_ap_reviewe_ec605d_idx')],
            },
        ),
    ]
