# Generated by Django 6.0 on 2026-03-05 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_jobapplicationchat_jobapplicationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('one_time_setup_fee', models.DecimalField(decimal_places=2, default=36000, max_digits=10)),
                ('free_hr_logins', models.PositiveIntegerField(default=5)),
                ('extra_hr_login_price', models.DecimalField(decimal_places=2, default=3500, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('purchased_hr_seats', models.PositiveIntegerField(default=0)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='employer.employerprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employer.employersubscriptionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerPayUPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription'), ('hr_seat', 'HR Seat')], default='subscription', max_length=20)),
                ('seats', models.PositiveIntegerField(default=0)),
                ('txnid', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('payu_payment_id', models.CharField(blank=True, max_length=100)),
                ('bank_ref_num', models.CharField(blank=True, max_length=100)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employer.employerprofile')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employersubscriptionplan')),
            ],
            options={
                'verbose_name': 'Employer PayU Payment',
                'verbose_name_plural': 'Employer PayU Payments',
                'db_table': 'employer_payu_payments',
            },
        ),
    ]
