# Generated by Django 6.0 on 2026-03-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0016_employersubscriptionplan_employersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerpayupayment',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
