# Generated by Django 5.2.4 on 2025-08-06 07:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('job_status', models.CharField(choices=[('actively_looking', 'Actively looking'), ('open_to_opportunities', 'Open to opportunities'), ('not_looking', 'Not looking'), ('employed', 'Currently employed')], default='actively_looking', max_length=25)),
                ('preferred_job_types', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('profile_visibility', models.BooleanField(default=True)),
                ('allow_recruiter_contact', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker Profile',
                'verbose_name_plural': 'Job Seeker Profiles',
                'db_table': 'jobseeker_profiles',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Resume title (e.g., 'Software Developer Resume')", max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='Primary/default resume')),
                ('is_active', models.BooleanField(default=True)),
                ('experience_level', models.CharField(blank=True, choices=[('fresher', 'Fresher (0-1 years)'), ('junior', 'Junior (1-3 years)'), ('mid_level', 'Mid-level (3-5 years)'), ('senior', 'Senior (5-8 years)'), ('lead', 'Lead/Principal (8+ years)'), ('executive', 'Executive/Director (10+ years)')], max_length=20)),
                ('total_experience_years', models.PositiveIntegerField(default=0)),
                ('total_experience_months', models.PositiveIntegerField(default=0)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('current_designation', models.CharField(blank=True, max_length=200)),
                ('current_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('notice_period', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('15_days', '15 days'), ('1_month', '1 month'), ('2_months', '2 months'), ('3_months', '3 months')], max_length=20)),
                ('education_data', models.JSONField(blank=True, default=list)),
                ('work_experience_data', models.JSONField(blank=True, default=list)),
                ('skills_data', models.JSONField(blank=True, default=list)),
                ('certifications_data', models.JSONField(blank=True, default=list)),
                ('projects_data', models.JSONField(blank=True, default=list)),
                ('languages_data', models.JSONField(blank=True, default=list)),
                ('achievements_data', models.JSONField(blank=True, default=list)),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='resumes/pdf/')),
                ('resume_doc', models.FileField(blank=True, null=True, upload_to='resumes/doc/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.PositiveIntegerField(default=0)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='jobseaker.jobseekerprofile')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'db_table': 'jobseeker_resumes',
                'indexes': [models.Index(fields=['profile', 'is_default'], name='jobseeker_r_profile_6c61e1_idx'), models.Index(fields=['is_active'], name='jobseeker_r_is_acti_f753d2_idx'), models.Index(fields=['experience_level'], name='jobseeker_r_experie_9f952d_idx'), models.Index(fields=['created_at'], name='jobseeker_r_created_cd333b_idx')],
                'unique_together': {('profile', 'title')},
            },
        ),
    ]
