# Generated by Django 5.2.4 on 2025-08-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='dream_companies',
            field=models.JSONField(blank=True, default=list, help_text='List of dream companies'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_roles',
            field=models.JSONField(blank=True, default=list, help_text='Roles the job seeker is interested in'),
        ),
    ]
