# Generated by Django 5.2.4 on 2025-09-05 08:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseaker', '0003_airemarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('freemium', 'Freemium'), ('premium', 'Premium')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_swipe_limit', models.PositiveIntegerField(default=20)),
                ('has_advanced_cards', models.BooleanField(default=False)),
                ('has_verified_jobs', models.BooleanField(default=False)),
                ('mock_interviews_monthly', models.PositiveIntegerField(default=0)),
                ('has_profile_review', models.BooleanField(default=False)),
                ('has_skill_training', models.BooleanField(default=False)),
                ('has_hyresense', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('daily_swipes_used', models.PositiveIntegerField(default=0)),
                ('swipe_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('monthly_interviews_used', models.PositiveIntegerField(default=0)),
                ('monthly_reset_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='jobseaker.jobseekerprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseaker.subscriptionplan')),
            ],
            options={
                'db_table': 'jobseeker_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseaker.jobseekerprofile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobseaker.jobseekersubscription')),
            ],
            options={
                'db_table': 'razorpay_payments',
            },
        ),
    ]
