# Generated by Django 5.2.4 on 2025-11-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseaker', '0004_subscriptionplan_jobseekersubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaypayment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
