# Generated by Django 5.2.4 on 2025-11-28 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseaker', '0005_razorpaypayment_razorpay_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razorpaypayment',
            old_name='subscription',
            new_name='jobseeker_subscription',
        ),
        migrations.AddField(
            model_name='razorpaypayment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobseaker.subscriptionplan'),
        ),
    ]
