# Generated by Django 5.2.4 on 2025-12-25 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseaker', '0006_rename_subscription_razorpaypayment_jobseeker_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expert_name', models.CharField(blank=True, max_length=150)),
                ('expert_designation', models.CharField(blank=True, max_length=150)),
                ('expert_company', models.CharField(blank=True, max_length=150)),
                ('interview_type', models.CharField(choices=[('behavioral', 'Behavioral & Situational'), ('technical', 'Technical Round'), ('dsa', 'Data Structures & Algorithms'), ('system_design', 'System Design'), ('hr', 'HR Interview')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from job seeker.')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Rating given by the interviewer (1 to 5)', max_digits=3, null=True)),
                ('feedback', models.TextField(blank=True, help_text="Expert's feedback after the interview")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by_admin', models.BooleanField(default=False)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to='jobseaker.jobseekerprofile')),
            ],
            options={
                'db_table': 'mock_interviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
