# Generated by Django 5.2.4 on 2025-12-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseaker', '0007_mockinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockinterview',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
