# Generated by Django 6.0 on 2026-02-28 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseaker', '0008_alter_mockinterview_date_alter_mockinterview_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayUPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txnid', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('payu_payment_id', models.CharField(blank=True, max_length=100)),
                ('bank_ref_num', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobseaker.jobseekerprofile')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobseaker.subscriptionplan')),
            ],
            options={
                'db_table': 'payu_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
