# Generated by Django 6.0 on 2026-02-28 18:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseaker', '0009_payupayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to='jobseaker.payupayment')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to='jobseaker.jobseekersubscription')),
            ],
            options={
                'db_table': 'subscription_activations',
            },
        ),
    ]
